# Docker Compose File for Development / Single Machine Deployments
# Creates an Nginx, Django, and Postgres container that work
# together.

version: "3"
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
services:
  presqt_nginx:
    depends_on:
      - presqt_django
    image: nginx:1.15
    networks:
      - frontend
    ports:
      # This ties host port 8000 to nginx container port 80
      # Inside of the nginx config, it's port 80 it forwarded to Django 8000
      # It is a little confusing.
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./config/ssl:/etc/ssl
      - ./config/nginx/conf.d/${ENVIRONMENT}_local.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/snippets:/etc/nginx/snippets
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./announcements:/usr/src/app/announcements
      - presqt_ui_volume:/usr/src/app/ui
      - presqt_static_volume:/usr/src/app/staticfiles
      - presqt_media_volume:/usr/src/app/mediafiles
      - nginx_logs_volume:/var/log/nginx/

  # Create a Django container. Note that no secrets should
  # be stored within the container, but passed in via
  # environment variables.
  presqt_django:
    command: "docker/django_entrypoint.sh"
    build:
      context: .
      dockerfile: django.dockerfile

      # "Build Args" don't persist into the running
      # container, so we prefix them with BUILD to
      # make this clear.
      args:
        BUILD_ENVIRONMENT: ${ENVIRONMENT:-production}
    environment:
      CURATE_ND_TEST_TOKEN: $CURATE_ND_TEST_TOKEN
      GITHUB_TEST_USER_TOKEN: $GITHUB_TEST_USER_TOKEN
      GITLAB_TEST_USER_TOKEN: $GITLAB_TEST_USER_TOKEN
      GITLAB_UPLOAD_TEST_USER_TOKEN: $GITLAB_UPLOAD_TEST_USER_TOKEN
      OSF_TEST_USER_TOKEN: $OSF_TEST_USER_TOKEN
      OSF_PRIVATE_USER_TOKEN: $OSF_PRIVATE_USER_TOKEN
      OSF_UPLOAD_TEST_USER_TOKEN: $OSF_UPLOAD_TEST_USER_TOKEN
      OSF_PRESQT_FORK_TOKEN: $OSF_PRESQT_FORK_TOKEN
      ZENODO_TEST_USER_TOKEN: $ZENODO_TEST_USER_TOKEN
      FIGSHARE_TEST_USER_TOKEN: $FIGSHARE_TEST_USER_TOKEN
      SECRET_KEY: $SECRET_KEY
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DJANGO_SETTINGS_MODULE: config.settings.${ENVIRONMENT:-production}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER:-NA}
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      APPLICATION_USER: $APPLICATION_USER
      APPLICATION_PASSWORD: $APPLICATION_PASSWORD
      APPLICATION_DB: $APPLICATION_DB
      ORCID_CLIENT_ID: $ORCID_CLIENT_ID
      ORCID_CLIENT_SECRET: $ORCID_CLIENT_SECRET
      TOKEN_KEY: $TOKEN_KEY
    restart: always
    depends_on: 
      - postgres_db
    volumes:
      - .:/usr/src/app
      - presqt_static_volume:/usr/src/app/staticfiles
      - presqt_media_volume:/usr/src/app/mediafiles
    networks:
      - frontend
      - backend
  
  # Since only one service should be running
  # per container, we need something separate
  # to run scheduled jobs.
  presqt_cron:
    command: "docker/cron_startup.sh"
    restart: always
    depends_on:
      - presqt_django
    build:
      context: .
      dockerfile: django.dockerfile
      args:
        BUILD_ENVIRONMENT: ${ENVIRONMENT:-production}
    environment:
      CURATE_ND_TEST_TOKEN: $CURATE_ND_TEST_TOKEN
      GITHUB_TEST_USER_TOKEN: $GITHUB_TEST_USER_TOKEN
      GITLAB_TEST_USER_TOKEN: $GITLAB_TEST_USER_TOKEN
      GITLAB_UPLOAD_TEST_USER_TOKEN: $GITLAB_UPLOAD_TEST_USER_TOKEN
      OSF_TEST_USER_TOKEN: $OSF_TEST_USER_TOKEN
      OSF_PRIVATE_USER_TOKEN: $OSF_PRIVATE_USER_TOKEN
      OSF_UPLOAD_TEST_USER_TOKEN: $OSF_UPLOAD_TEST_USER_TOKEN
      OSF_PRESQT_FORK_TOKEN: $OSF_PRESQT_FORK_TOKEN
      ZENODO_TEST_USER_TOKEN: $ZENODO_TEST_USER_TOKEN
      FIGSHARE_TEST_USER_TOKEN: $FIGSHARE_TEST_USER_TOKEN
      SECRET_KEY: $SECRET_KEY
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DJANGO_SETTINGS_MODULE: config.settings.${ENVIRONMENT:-production}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER:-NA}
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      APPLICATION_USER: $APPLICATION_USER
      APPLICATION_PASSWORD: $APPLICATION_PASSWORD
      APPLICATION_DB: $APPLICATION_DB
      ORCID_CLIENT_ID: $ORCID_CLIENT_ID
      ORCID_CLIENT_SECRET: $ORCID_CLIENT_SECRET
      TOKEN_KEY: $TOKEN_KEY
    volumes:
      - .:/usr/src/app
      - presqt_static_volume:/usr/src/app/staticfiles
      - presqt_media_volume:/usr/src/app/mediafiles
      - ./config/cron/crontabs/${ENVIRONMENT:-production}.crontab:/etc/crontabs/root
    networks:
      - backend

  presqt_nginx_logger:
    command: "docker/nginx_logger_startup.sh"
    restart: always
    depends_on:
      - presqt_nginx
    build:
      context: .
      dockerfile: django.dockerfile
      args:
        BUILD_ENVIRONMENT: ${ENVIRONMENT:-production}
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-production}
    volumes:
      - .:/usr/src/app
      - nginx_logs_volume:/var/log/nginx/

  # This will create a Postgres container with persistent
  # storage on the host. It's important to note that unless
  # you delete the persistant storage volume, the password
  # set via environment variable at the first run of docker-compose
  # will also persist, even if you change the environment
  # variable value in between docker-compose invocations.
  postgres_db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-production}
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      APPLICATION_USER: $APPLICATION_USER
      APPLICATION_PASSWORD: $APPLICATION_PASSWORD
      APPLICATION_DB: $APPLICATION_DB
    networks:
      - backend
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data

# We create two top-level networks to provide some isolation
# of concerns / greater security. In our case, we use this to
# disallow direct connections between the NGINX container and
# the Postgres container.
networks:
  frontend:
  backend:

volumes:
  presqt_static_volume:
  presqt_media_volume:
  presqt_ui_volume:
  nginx_logs_volume:
  postgres_volume:        # Store the postgres database data. Only linked with postgres.
