
#!/bin/bash
# Create the application database and user in Postgres.

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $APPLICATION_USER WITH PASSWORD '$APPLICATION_PASSWORD';
    CREATE DATABASE $APPLICATION_DB;
    ALTER USER $APPLICATION_USER CREATEDB;
    GRANT ALL PRIVILEGES ON DATABASE $APPLICATION_DB TO $APPLICATION_USER;
EOSQL